In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Contoh output model untuk 3 sampel (misalnya, 3 gambar)
# Setiap baris mewakili satu sampel, dan setiap kolom mewakili skor untuk setiap kelas (kucing, anjing, burung)
output = torch.tensor([[2.0, 1.0, 0.1],  # Output untuk sampel 1
                       [0.5, 3.0, 1.5],  # Output untuk sampel 2
                       [1.2, 0.8, 2.5]]) # Output untuk sampel 3

# Label sebenarnya untuk 3 sampel ini
# Sampel 1 adalah kucing (kelas 0)
# Sampel 2 adalah anjing (kelas 1)
# Sampel 3 adalah burung (kelas 2)
target = torch.tensor([0, 1, 2])

# Inisialisasi fungsi CrossEntropyLoss
criterion = nn.CrossEntropyLoss()

# Hitung loss
loss = criterion(output, target)

print(f"Output model:\n{output}")
print(f"Label sebenarnya:\n{target}")
print(f"Loss (CrossEntropyLoss): {loss.item():.4f}")

# Mari kita hitung loss secara manual untuk pemahaman yang lebih dalam

# 1. Softmax untuk setiap sampel
probabilities = F.softmax(output, dim=1) # dim=1 karena kita ingin menerapkan Softmax di sepanjang dimensi kelas
print(f"\nProbabilitas setelah Softmax:\n{probabilities}")

# 2. Negative Log Likelihood untuk setiap sampel
# Kita perlu mengambil probabilitas dari kelas yang benar untuk setiap sampel
# Untuk sampel 1 (target 0): probabilities[0, 0]
# Untuk sampel 2 (target 1): probabilities[1, 1]
# Untuk sampel 3 (target 2): probabilities[2, 2]

log_probabilities = torch.log(probabilities)
nll_loss_manual = torch.zeros(target.size(0)) # Inisialisasi tensor untuk menyimpan loss per sampel

for i in range(target.size(0)):
    nll_loss_manual[i] = -log_probabilities[i, target[i]]

print(f"\nNegative Log Likelihood Loss (per sampel):\n{nll_loss_manual}")

# 3. Rata-rata NLL Loss di seluruh sampel
mean_nll_loss_manual = torch.mean(nll_loss_manual)
print(f"\nRata-rata Negative Log Likelihood Loss (manual): {mean_nll_loss_manual.item():.4f}")

# Perhatikan bahwa loss yang dihitung oleh nn.CrossEntropyLoss sama dengan rata-rata NLL Loss manual
assert torch.allclose(loss, mean_nll_loss_manual)

Output model:
tensor([[2.0000, 1.0000, 0.1000],
        [0.5000, 3.0000, 1.5000],
        [1.2000, 0.8000, 2.5000]])
Label sebenarnya:
tensor([0, 1, 2])
Loss (CrossEntropyLoss): 0.3529

Probabilitas setelah Softmax:
tensor([[0.6590, 0.2424, 0.0986],
        [0.0629, 0.7662, 0.1710],
        [0.1873, 0.1255, 0.6872]])

Negative Log Likelihood Loss (per sampel):
tensor([0.4170, 0.2664, 0.3752])

Rata-rata Negative Log Likelihood Loss (manual): 0.3529
